// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type lecturesTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *lecturesTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("lectures").
func (v *lecturesTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *lecturesTableType) Columns() []string {
	return []string{
		"id",
		"title",
		"text",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *lecturesTableType) NewStruct() reform.Struct {
	return new(Lectures)
}

// NewRecord makes a new record for that table.
func (v *lecturesTableType) NewRecord() reform.Record {
	return new(Lectures)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *lecturesTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// LecturesTable represents lectures view or table in SQL database.
var LecturesTable = &lecturesTableType{
	s: parse.StructInfo{
		Type:    "Lectures",
		SQLName: "lectures",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "Title", Type: "string", Column: "title"},
			{Name: "Text", Type: "string", Column: "text"},
		},
		PKFieldIndex: 0,
	},
	z: new(Lectures).Values(),
}

// String returns a string representation of this struct or record.
func (s Lectures) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Title: " + reform.Inspect(s.Title, true)
	res[2] = "Text: " + reform.Inspect(s.Text, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Lectures) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Title,
		s.Text,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Lectures) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Title,
		&s.Text,
	}
}

// View returns View object for that struct.
func (s *Lectures) View() reform.View {
	return LecturesTable
}

// Table returns Table object for that record.
func (s *Lectures) Table() reform.Table {
	return LecturesTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Lectures) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Lectures) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Lectures) HasPK() bool {
	return s.ID != LecturesTable.z[LecturesTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Lectures) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = LecturesTable
	_ reform.Struct = (*Lectures)(nil)
	_ reform.Table  = LecturesTable
	_ reform.Record = (*Lectures)(nil)
	_ fmt.Stringer  = (*Lectures)(nil)
)

func init() {
	parse.AssertUpToDate(&LecturesTable.s, new(Lectures))
}
