// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type quizTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *quizTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("quiz").
func (v *quizTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *quizTableType) Columns() []string {
	return []string{
		"id",
		"title",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *quizTableType) NewStruct() reform.Struct {
	return new(Quiz)
}

// NewRecord makes a new record for that table.
func (v *quizTableType) NewRecord() reform.Record {
	return new(Quiz)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *quizTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// QuizTable represents quiz view or table in SQL database.
var QuizTable = &quizTableType{
	s: parse.StructInfo{
		Type:    "Quiz",
		SQLName: "quiz",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "Title", Type: "string", Column: "title"},
		},
		PKFieldIndex: 0,
	},
	z: new(Quiz).Values(),
}

// String returns a string representation of this struct or record.
func (s Quiz) String() string {
	res := make([]string, 2)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Title: " + reform.Inspect(s.Title, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Quiz) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Title,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Quiz) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Title,
	}
}

// View returns View object for that struct.
func (s *Quiz) View() reform.View {
	return QuizTable
}

// Table returns Table object for that record.
func (s *Quiz) Table() reform.Table {
	return QuizTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Quiz) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Quiz) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Quiz) HasPK() bool {
	return s.ID != QuizTable.z[QuizTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *Quiz) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = QuizTable
	_ reform.Struct = (*Quiz)(nil)
	_ reform.Table  = QuizTable
	_ reform.Record = (*Quiz)(nil)
	_ fmt.Stringer  = (*Quiz)(nil)
)

func init() {
	parse.AssertUpToDate(&QuizTable.s, new(Quiz))
}
