// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type quizQuestionsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *quizQuestionsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("quiz_questions").
func (v *quizQuestionsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *quizQuestionsTableType) Columns() []string {
	return []string{
		"id",
		"question",
		"correct_answer_id",
		"quiz_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *quizQuestionsTableType) NewStruct() reform.Struct {
	return new(QuizQuestions)
}

// NewRecord makes a new record for that table.
func (v *quizQuestionsTableType) NewRecord() reform.Record {
	return new(QuizQuestions)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *quizQuestionsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// QuizQuestionsTable represents quiz_questions view or table in SQL database.
var QuizQuestionsTable = &quizQuestionsTableType{
	s: parse.StructInfo{
		Type:    "QuizQuestions",
		SQLName: "quiz_questions",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "Question", Type: "string", Column: "question"},
			{Name: "CorrectAnswerID", Type: "*int32", Column: "correct_answer_id"},
			{Name: "QuizID", Type: "*int32", Column: "quiz_id"},
		},
		PKFieldIndex: 0,
	},
	z: new(QuizQuestions).Values(),
}

// String returns a string representation of this struct or record.
func (s QuizQuestions) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Question: " + reform.Inspect(s.Question, true)
	res[2] = "CorrectAnswerID: " + reform.Inspect(s.CorrectAnswerID, true)
	res[3] = "QuizID: " + reform.Inspect(s.QuizID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *QuizQuestions) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Question,
		s.CorrectAnswerID,
		s.QuizID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *QuizQuestions) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Question,
		&s.CorrectAnswerID,
		&s.QuizID,
	}
}

// View returns View object for that struct.
func (s *QuizQuestions) View() reform.View {
	return QuizQuestionsTable
}

// Table returns Table object for that record.
func (s *QuizQuestions) Table() reform.Table {
	return QuizQuestionsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *QuizQuestions) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *QuizQuestions) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *QuizQuestions) HasPK() bool {
	return s.ID != QuizQuestionsTable.z[QuizQuestionsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *QuizQuestions) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = QuizQuestionsTable
	_ reform.Struct = (*QuizQuestions)(nil)
	_ reform.Table  = QuizQuestionsTable
	_ reform.Record = (*QuizQuestions)(nil)
	_ fmt.Stringer  = (*QuizQuestions)(nil)
)

func init() {
	parse.AssertUpToDate(&QuizQuestionsTable.s, new(QuizQuestions))
}
