// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type userAnswersTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *userAnswersTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("user_answers").
func (v *userAnswersTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *userAnswersTableType) Columns() []string {
	return []string{
		"id",
		"user_id",
		"question_id",
		"answer_id",
		"is_correct",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *userAnswersTableType) NewStruct() reform.Struct {
	return new(UserAnswers)
}

// NewRecord makes a new record for that table.
func (v *userAnswersTableType) NewRecord() reform.Record {
	return new(UserAnswers)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *userAnswersTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// UserAnswersTable represents user_answers view or table in SQL database.
var UserAnswersTable = &userAnswersTableType{
	s: parse.StructInfo{
		Type:    "UserAnswers",
		SQLName: "user_answers",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int32", Column: "id"},
			{Name: "UserID", Type: "*int32", Column: "user_id"},
			{Name: "QuestionID", Type: "*int32", Column: "question_id"},
			{Name: "AnswerID", Type: "*int32", Column: "answer_id"},
			{Name: "IsCorrect", Type: "bool", Column: "is_correct"},
		},
		PKFieldIndex: 0,
	},
	z: new(UserAnswers).Values(),
}

// String returns a string representation of this struct or record.
func (s UserAnswers) String() string {
	res := make([]string, 5)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "UserID: " + reform.Inspect(s.UserID, true)
	res[2] = "QuestionID: " + reform.Inspect(s.QuestionID, true)
	res[3] = "AnswerID: " + reform.Inspect(s.AnswerID, true)
	res[4] = "IsCorrect: " + reform.Inspect(s.IsCorrect, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *UserAnswers) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.UserID,
		s.QuestionID,
		s.AnswerID,
		s.IsCorrect,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *UserAnswers) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.UserID,
		&s.QuestionID,
		&s.AnswerID,
		&s.IsCorrect,
	}
}

// View returns View object for that struct.
func (s *UserAnswers) View() reform.View {
	return UserAnswersTable
}

// Table returns Table object for that record.
func (s *UserAnswers) Table() reform.Table {
	return UserAnswersTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *UserAnswers) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *UserAnswers) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *UserAnswers) HasPK() bool {
	return s.ID != UserAnswersTable.z[UserAnswersTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ID = pk.
func (s *UserAnswers) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = UserAnswersTable
	_ reform.Struct = (*UserAnswers)(nil)
	_ reform.Table  = UserAnswersTable
	_ reform.Record = (*UserAnswers)(nil)
	_ fmt.Stringer  = (*UserAnswers)(nil)
)

func init() {
	parse.AssertUpToDate(&UserAnswersTable.s, new(UserAnswers))
}
